# -*- coding: utf-8 -*-
"""regression-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUDAy4Nzwu3d4njDDCgjbtJ5-r4FFcyl
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

# Sample dataset: Years of Experience vs Salary
data = {
    'YearsExperience': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Salary': [30000, 35000, 40000, 50000, 55000, 65000, 70000, 80000, 85000, 95000]
}

df_data = pd.DataFrame(data)

# Define X and y
X = df_data[['YearsExperience']]
y = df_data['Salary']

# Train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Function to take user input
def user_input_features():
    years_exp = st.sidebar.slider(
        'Years of Experience',
        float(X['YearsExperience'].min()),
        float(X['YearsExperience'].max()),
        float(X['YearsExperience'].mean())
    )

    data = {'YearsExperience': years_exp}
    features = pd.DataFrame(data, index=[0])
    return features

# Get user input
input_df = user_input_features()

# Display user input
st.subheader('User Input Feature')
st.write(input_df)

# Make prediction
prediction = model.predict(input_df)

# Display prediction
st.subheader('Predicted Salary')
st.write(f"₹ {prediction[0]:,.2f}")

# Display model details
st.subheader('Model Details')
st.write(f"Intercept: {model.intercept_:.2f}")
st.write(f"Coefficient: {model.coef_[0]:.2f}")
